// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetice.Models;

public partial class Brand
{
    public int BrandId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Country { get; set; }

    public DateOnly? DateFounded { get; set; }

    public string PictureUrl { get; set; }

    public string WebsiteUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}