// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetice.Models;

public partial class CustomListItem
{
    public int CustomListItemId { get; set; }

    public int CustomListId { get; set; }

    public int ProductId { get; set; }

    public DateTime? AddedAt { get; set; }

    public virtual CustomList CustomList { get; set; }

    public virtual Product Product { get; set; }
}