// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetice.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int BrandId { get; set; }

    public int CategoryId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public string CountryOfOrigin { get; set; }

    public decimal? Price { get; set; }

    public string SkinType { get; set; }

    public bool IsVegan { get; set; }

    public string Shade { get; set; }

    public string Ingredients { get; set; }

    public string Volume { get; set; }

    public string FinishType { get; set; }

    public decimal? AverageRating { get; set; }

    public int? ReviewCount { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Brand Brand { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<CustomListItem> CustomListItems { get; set; } = new List<CustomListItem>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}