// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetice.Models;

public partial class ReviewVote
{
    public int ReviewVoteId { get; set; }

    public int ReviewId { get; set; }

    public string UserId { get; set; }

    public bool IsLike { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Review Review { get; set; }
}