// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Cosmetice.Models;

public partial class ReviewReply
{
    public int ReplyId { get; set; }

    public int ReviewId { get; set; }

    public string UserId { get; set; } = null!;

    public int? ParentReplyId { get; set; }

    public string Content { get; set; } = null!;

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<ReviewReply> InverseParentReply { get; set; } = new List<ReviewReply>();

    public virtual ReviewReply? ParentReply { get; set; }

    public virtual Review Review { get; set; } = null!;
}